#!/bin/bash
#
# krellkam_load - rotates a list of images and URLs in ~/.krellkam.list
#
# Copyright (C) 2001 paul cannon
# space software lab/utah state university
# paul@cannon.cs.usu.edu
# Released under the GNU Public License (GPL)
#
# requires GNU wget for URL loads-
#   see http://www.gnu.org/software/wget/wget.html

function usage()
{
  cat << US_END

USAGE:

krellkam_load [options] [override]

If no command line parameters are given, krellkam_load examines the first
line of the file ~/.krellkam.list, and rotates it to the bottom. The line
can be a URL or a local path to an image file. The image is downloaded if
appropriate, and the location output to GKrellKam, so it knows where to
look.

OPTIONS:

If -r or --random is specified, then the list is not rotated. One line is
selected at random and downloaded if appropriate.

If -l <listfile> or --list <listfile> is specified, then listfile is
used instead of ~/.krellkam.list.

If a filename or URL is given on the command line (override), then the
list will be disregarded and the given image used.

US_END
}

function die()
{
  echo $* >&2
  exit 1
}

PICS_LIST=$HOME/.krellkam.list
FILELOC=$HOME/.krellkam.jpg
WGET="wget -q"

thispic=""
pick_rand=0

while [ -n "$1" ]; do
  if [ $1 == "-r" -o $1 == "--random" ]; then
    pick_rand=1
  elif [ $1 == "-l" -o $1 == "--list" ]; then
    shift
    PICS_LIST=$1
  elif [ $1 == "-h" -o $1 == "--help" ]; then
    usage
    exit 0
  else
    thispic="$1"
  fi
  shift
done

# check the list
test -r $PICS_LIST || die "Can't open listfile $PICS_LIST."
numpics=`cat $PICS_LIST | wc -l`
test $numpics -gt 0 || die "Listfile $PICS_LIST is empty."

if [ -z $thispic ]; then
  if [ $pick_rand == 1 ]; then
    # pick a random line from the file

    let num=($RANDOM%numpics)+1
    thispic=`head -$num $PICS_LIST | tail -1`
  else
    # rotate the list; first line goes to bottom
    TMPLOC=`mktemp /tmp/krellkam.XXXXXX`

    # remember the first line
    thispic=`head -1 $PICS_LIST`

    # rotate the list
    let num=numpics-1
    tail -$num $PICS_LIST > $TMPLOC
    echo $thispic >> $TMPLOC
    mv $TMPLOC $PICS_LIST
  fi
fi

# determine if URL or local file
if echo $thispic | grep "://" > /dev/null; then
	
  # Load URL..
  $WGET -O $FILELOC $thispic
  echo $FILELOC
	
else
	
  # Local image file..
  echo $thispic

fi
